version: '3.7'

#####################################################
# This Docker Compose file contains three services
#    Dependency-Track PostGres database
#    Dependency-Track API Server
#    Dependency-Track FrontEnd
#####################################################

volumes:
  dependency-track:
  postgres-data:
  
services:
  postgres:
    image: postgres
    networks:
      - dtrack-net
    environment:
      - POSTGRES_PASSWORD=dtrackP@ssword
      - POSTGRES_USER=dtrack
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    restart: unless-stopped

  apiserver:
    image: dependencytrack/apiserver
    networks:
      - mirada-test
      - dtrack-net
    depends_on:
      - postgres
    environment:
    # The Dependency-Track container can be configured using any of the
    # available configuration properties defined in:
    # https://docs.dependencytrack.org/getting-started/configuration/
    # All properties are upper case with periods replaced by underscores.
    #
    # Database Properties
      - ALPINE_DATABASE_MODE=external
      - ALPINE_DATABASE_URL=jdbc:postgresql://postgres:5432/dtrack
      - ALPINE_DATABASE_DRIVER=org.postgresql.Driver
      - ALPINE_DATABASE_USERNAME=dtrack
      - ALPINE_DATABASE_PASSWORD=dtrackP@ssword
      - ALPINE_DATABASE_POOL_ENABLED=true
      - ALPINE_DATABASE_POOL_MAX_SIZE=20
      - ALPINE_DATABASE_POOL_MIN_IDLE=10
      - ALPINE_DATABASE_POOL_IDLE_TIMEOUT=300000
      - ALPINE_DATABASE_POOL_MAX_LIFETIME=600000
    #
    # Optional LDAP Properties
    # Note: the below settings are for the openLDAP configuration used in docker, not the active directory configuration used in production
      - ALPINE_LDAP_ENABLED=true
      - ALPINE_LDAP_SERVER_URL=ldap://openldap_server_1
      - ALPINE_LDAP_BASEDN=dc=mirada-medical,dc=test
      - ALPINE_LDAP_SECURITY_AUTH=simple
      # TODO: switch the bind user to the service account
      - ALPINE_LDAP_BIND_USERNAME=cn=admin,dc=mirada-medical,dc=test
      - ALPINE_LDAP_BIND_PASSWORD=nocturnalWorm30
      - ALPINE_LDAP_AUTH_USERNAME_FORMAT=%s
      - ALPINE_LDAP_ATTRIBUTE_NAME=cn
      - ALPINE_LDAP_ATTRIBUTE_MAIL=mail
      - ALPINE_LDAP_GROUPS_FILTER=(&(objectClass=groupOfUniqueNames))
      - ALPINE_LDAP_USER_GROUPS_FILTER=(&(objectClass=groupOfUniqueNames)(uniqueMember={USER_DN},{BASE_DN}))
      - ALPINE_LDAP_GROUPS_SEARCH_FILTER=(&(objectClass=groupOfUniqueNames)(cn=*{SEARCH_TERM}*))
      - ALPINE_LDAP_USERS_SEARCH_FILTER=(&(objectClass=inetOrgPerson)(cn=*{SEARCH_TERM}*))
      - ALPINE_LDAP_USER_PROVISIONING=false
      - ALPINE_LDAP_TEAM_SYNCHRONIZATION=false
    #
    # Optional OpenID Connect (OIDC) Properties
    # - ALPINE_OIDC_ENABLED=true
    # - ALPINE_OIDC_ISSUER=https://auth.example.com/auth/realms/example
    # - ALPINE_OIDC_CLIENT_ID=
    # - ALPINE_OIDC_USERNAME_CLAIM=preferred_username
    # - ALPINE_OIDC_TEAMS_CLAIM=groups
    # - ALPINE_OIDC_USER_PROVISIONING=true
    # - ALPINE_OIDC_TEAM_SYNCHRONIZATION=true
    #
    # Optional HTTP Proxy Settings
    # - ALPINE_HTTP_PROXY_ADDRESS=proxy.example.com
    # - ALPINE_HTTP_PROXY_PORT=8888
    # - ALPINE_HTTP_PROXY_USERNAME=
    # - ALPINE_HTTP_PROXY_PASSWORD=
    # - ALPINE_NO_PROXY=
    #
    # Optional Cross-Origin Resource Sharing (CORS) Headers
    # - ALPINE_CORS_ENABLED=true
    # - ALPINE_CORS_ALLOW_ORIGIN=*
    # - ALPINE_CORS_ALLOW_METHODS=GET POST PUT DELETE OPTIONS
    # - ALPINE_CORS_ALLOW_HEADERS=Origin, Content-Type, Authorization, X-Requested-With, Content-Length, Accept, Origin, X-Api-Key, X-Total-Count, *
    # - ALPINE_CORS_EXPOSE_HEADERS=Origin, Content-Type, Authorization, X-Requested-With, Content-Length, Accept, Origin, X-Api-Key, X-Total-Count
    # - ALPINE_CORS_ALLOW_CREDENTIALS=true
    # - ALPINE_CORS_MAX_AGE=3600
    deploy:
      resources:
        limits:
          memory: 12288m
        reservations:
          memory: 8192m
      restart_policy:
        condition: on-failure
    ports:
      - '8210:8080'
    volumes:
      - 'dependency-track:/data'
    restart: unless-stopped

  frontend:
    image: dependencytrack/frontend
    networks:
      - dtrack-net
    depends_on:
      - apiserver
    environment:
      # The base URL of the API server.
      # NOTE:
      #   * This URL must be reachable by the browsers of your users.
      #   * The frontend container itself does NOT communicate with the API server directly, it just serves static files.
      #   * When deploying to dedicated servers, please use the external IP or domain of the API server.
      - API_BASE_URL=http://localhost:8110
      # - "OIDC_ISSUER="
      # - "OIDC_CLIENT_ID="
      # - "OIDC_SCOPE="
      # - "OIDC_FLOW="
      # - "OIDC_LOGIN_BUTTON_TEXT="
      # volumes:
      # - "/host/path/to/config.json:/app/static/config.json"
    ports:
      - "8200:8080"
    restart: unless-stopped

networks:
  dtrack-net:
  mirada-test:
    external: true
    name: mirada-test
