version: '3.7'

services:
  # server container to run the actual ldap queries against, pulled from docker-hub
  server:
    build: .
    networks:
      - main
      - ldap-net
    environment:
      LDAP_ADMIN_PASSWORD: nocturnalWorm30 # given this is a local cluster, leaving the password is acceptable for now.
      LDAP_ORGANISATION: Amanshu
      LDAP_DOMAIN: amanshu.test
    ports:
      - '389:389'
      - '636:636'
    volumes:
      - ./data:/var/lib/ldap
      - ./config:/etc/ldap/slapd.d

  # admin container to allow frontend access to the ldap system, pulled from docker-hub
  admin:
    image: osixia/phpldapadmin:latest
    networks:
      - ldap-net
    ports:
      - '8100:80'
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: server
      PHPLDAPADMIN_HTTPS: 'false'
    volumes:
      - admin:/var/www/phpldapadmin
    depends_on:
      - server

volumes:
  data:
  config:
  admin:

networks:
  ldap-net:
  main:
    external: true
    name: main
