version: '3.7'

volumes:
  jenkins-home:
  
services:
  controller:
    build: .
    networks:
      - main
      - jenkins-net
    environment:
      - Version=1.0
    ports:
      - '8300:8080'
      - '50000:50000'
    volumes:
      - 'jenkins-home:/var/jenkins_home'
    restart: unless-stopped

networks:
  jenkins-net:
  main:
    external: true
    name: main
