version: '3.7'

volumes:
  jenkins-home:
  
services:
  controller:
    build:
      context: .
      args:
        Version: 1.0
    networks:
      - main
      - jenkins-net
    ports:
      - '8300:8080'
      - '50000:50000'
    volumes:
      - './data:/var/jenkins_home'
      - './config:/jenkins_setup'
    restart: unless-stopped

networks:
  jenkins-net:
  main:
    external: true
    name: main
