version: '3.7'

volumes:
  jenkins-home:
  
services:
  controller:
    build:
      context: .
      args:
        Version: 1.0
        GIT_COMMIT: $(git rev-parse HEAD)
    networks:
      - main
      - jenkins-net
    ports:
      - '8300:8080'
      - '50000:50000'
    volumes:
      - 'jenkins-home:/var/jenkins_home'
    restart: unless-stopped

networks:
  jenkins-net:
  main:
    external: true
    name: main
